anchor_version = "0.24.2"
solana_version = "1.9.29"

[features]
seeds = true

[programs.localnet]
sure_pool = "D47wvD2bTDXR9XqqHdP8bwYSXu2QPMW6fGHg2aEBKunM"
oracle = "2prR7H6LfRqwiP2iTyZG1suG4B3zU6JEpUBXWeQB66qH"

[programs.devnet]
sure_pool = "D47wvD2bTDXR9XqqHdP8bwYSXu2QPMW6fGHg2aEBKunM"

[programs.testnet]
sure_pool = "D47wvD2bTDXR9XqqHdP8bwYSXu2QPMW6fGHg2aEBKunM"

[registry]
url = "https://github.com/Sure-Protocol/sure-v1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*test.ts"

[test] 
startup_wait = 20000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/mpl_token_metadata.so"

[[test.genesis]]
address = "GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH"
program = "./deps/smart_wallet.so"

[[test.genesis]]
address = "Govz1VyoyLD5BL6CSCxUJLVLsQHRwjfFj1prNsdNg5Jw"
program = "./deps/govern.so"

[[test.genesis]]
address = "LocktDzaV1W2Bm9DeZeiyz4J9zs4fRqNiYqQyracRXw"
program = "./deps/locked_voter.so"



