[features]
seeds = false

[programs.localnet]
sure_pool = "sureLJ8UXoy3WF3Dk6Hy1ak8DscZkmHvv1hprvhVCxB"

[programs.devnet]
sure_pool = "sureLJ8UXoy3WF3Dk6Hy1ak8DscZkmHvv1hprvhVCxB"

[registry]
url = "https://github.com/Sure-Protocol/sure-v1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/mpl_token_metadata.so"
