FROM node:alpine AS build


COPY lerna.json /dapp/lerna.json
COPY package.json /dapp/package.json
COPY tsconfig.json /dapp/tsconfig.json
COPY packages/app/ /dapp/packages/app/
WORKDIR /dapp/

RUN apk add git \
    && yarn set version stable \
    && ls -la \
    && yarn --version \
    && yarn \
    && yarn build:craco


FROM nginx
COPY --from=build /dapp/packages/app/build/ /usr/share/nginx/html/
