FROM node:alpine AS build

WORKDIR /dapp/
COPY .yarn .yarn
COPY yarn.lock yarn.lock
COPY .yarnrc.yml .yarnrc.yml
COPY lerna.json lerna.json
COPY package.json package.json
COPY tsconfig.json tsconfig.json
COPY packages/app/ packages/app/


RUN apk add git \
    && yarn set version stable \
    && yarn \
    && yarn build:craco


FROM nginx
COPY --from=build /dapp/packages/app/build/ /usr/share/nginx/html/
